katt = require './katt'

module.exports =
  PROTOCOL_HTTP: 'http:'
  PROTOCOL_HTTPS: 'https:'
  DEFAULT_SCENARIO_TIMEOUT: 120000
  DEFAULT_REQUEST_TIMEOUT: 20000
  DEFAULT_PROTOCOL: 'http:'
  DEFAULT_HOSTNAME: '127.0.0.1'
  DEFAULT_PORT_HTTP: 80
  DEFAULT_PORT_HTTPS: 443
  DEFAULT_PARSE_FUNCTION: katt.parse
  DEFAULT_REQUEST_FUNCTION: katt.request
  DEFUALT_VALIDATE_FUNCTION: katt.validate
